version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12.7

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            go get -u golang.org/x/lint/golint
      - run: make lint
      - run: make test
      - run: make build

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install deploy tool
          command: |
            cd scripts/deploy
            go install .
      - run:
          name: Deploy binaries
          command: |
            make binaries
            deploy "$CIRCLE_TAG" bow_darwin_amd64
            deploy "$CIRCLE_TAG" bow_linux_amd64
            deploy "$CIRCLE_TAG" bow_windows_amd64.exe

workflows:
  version: 2
  build:
    jobs:
      - build
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
